# Generated by Django 5.2.1 on 2026-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='background/', verbose_name='Imagen de portada')),
                ('biography_image', models.ImageField(upload_to='background/', verbose_name='Imagen de biografía')),
                ('portfolio_image', models.ImageField(upload_to='background/', verbose_name='Imagen de portafolio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-created'],
            },
        ),
    ]
