# Generated by Django 5.2.1 on 2026-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ocupation',
            new_name='occupation',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=10, verbose_name='Edad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='hola', verbose_name='Biografía'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='my_avatar',
            field=models.ImageField(default=None, upload_to='avatars/', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
