# Generated by Django 5.2.1 on 2026-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_rename_ocupation_profile_occupation_profile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='miguel@gmail.com', max_length=100, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=3182067714, max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
